[project]

name = "psion-software-index"
version = "0.0.0"
description = "Tools for building the Psion Software Index"
requires-python = "==3.12.*"

dependencies = [
    "b2sdk",
    "beautifulsoup4",
    "certifi",
    "check-jsonschema",
    "fastcommand",
    "jinja2",
    "jsonschema",
    "matplotlib",
    "natsort",
    "pillow",
    "python-frontmatter",
    "pyyaml",
    "requests",
    "tqdm",
]

[project.scripts]

charts = "tools.charts:main"
indexer = "tools.indexer:main"
manage = "tools.manage:main"
query = "tools.query:main"
snapshot = "tools.snapshot:main"

[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]

packages = ["tools"]
