source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"
gem "webrick", "~> 1.9.0"
gem "rexml", ">= 3.3.3"
gem 'jekyll-typogrify'
gem 'jekyll-gfm-admonitions'

gem "base64"
gem "bigdecimal"
gem "csv"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]
