name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted-macos-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build the index
      env:
        INDEXER_ASSETS_DIRECTORY: /Users/jbmorley/psion-software-index/assets
      run: |
        mkdir -p "$INDEXER_ASSETS_DIRECTORY"
        tools/indexer libraries/full.yaml sync index overlay

    - name: Build site
      run: |
        scripts/build-site.sh
        chmod -v -R +rX "_site/"

    - name: Deploy site
      # if: github.ref == 'refs/heads/main'
      env:
        ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
      run: |
        cd site
        ansible/deploy.py
