name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: ./install-dependencies.sh

    - name: Cache the assets
      uses: actions/cache@v4
      with:
        path: |
          assets
        key: ${{ runner.os }}-${{ hashFiles('build.sh') }}

    - name: Build and test
      run: ./build.sh
